### ISSUE TITLE
ocularDocumentDeskew with same buffer for Output & Input

### ISSUE THREAD

**Issue by hafedh-trimeche** [warrengalyen/ocular#2]
Is it possible to use the same buffer for **Input** & **Output** for **ocularDocumentDeskew**?

`ocularDocumentDeskew(Input,Input,Width,Height,Width*Channels);`
instead of
`ocularDocumentDeskew(Input,Output,Width,Height,Width*Channels);`

Which functions allows that?

Thank you for this valuable library.

**Comment by warrengalyen** [comment]
No, unfortunately not. There are few operations that allow "in-place" editing of an image.  Some examples would be brightness, contrast, threshold, invert and color space conversion. This operation it typically going to be limited to the color adjustment category.

**Comment by hafedh-trimeche** [comment]
Thank you for clarifications

**Comment by warrengalyen** [comment]
Glad you like the library! I still have many new features in the works. Had to take a break for a while to work on other projects, but should be adding to it the coming weeks.
