### ISSUE TITLE
Compiler eroors Visual Studio 2022

### ISSUE THREAD

**Issue by hafedh-trimeche** [warrengalyen/ocular#3]
Hi,
Please note these errors under Visual Studio 2022:
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2057	expected constant expression	ocular	D:\DevStudio\ocular\lib\threshold.c	33		
Error	C2466	cannot allocate an array of constant size 0	ocular	D:\DevStudio\ocular\lib\threshold.c	33		
Error	C2133	'S': unknown size	ocular	D:\DevStudio\ocular\lib\threshold.c	33		
Error	C2057	expected constant expression	ocular	D:\DevStudio\ocular\lib\threshold.c	34		
Error	C2466	cannot allocate an array of constant size 0	ocular	D:\DevStudio\ocular\lib\threshold.c	34		

```
Best regards.

**Comment by warrengalyen** [comment]
This is not a bug. Microsoft's compiler, "cl.exe", doesn't support variable length arrays. Wish there was a way to change the permissiveness of their compiler but it's just not implemented. It will compile fine under GCC or Clang. Thanks for reminding me of this. I will add a note to the build section of the readme.

**Comment by warrengalyen** [comment]
I was able to get the library to compile with VS 2022 with very little changes. There were far fewer modifications needed as I initially thought. I've pushed a fix.
